import { createContext, useContext, useState } from "react";

const LanguageContext = createContext();

export const translations = {
  en: {
    // Sidebar
    home: "Home",
    brainGames: "Brain Games",
    talkToSmriti: "Talk to Care Agent",
    dailyRoutine: "Daily Routine",
    medicineHealth: "Medicine & Health",
    memoryProgress: "Memory Progress",
    careCircle: "My Care Circle",
    safetyLocation: "Safety & Location",
    memoryBook: "Memory Book",
    language: "Language",
    helpSupport: "Help & Support",
    settings: "Settings",

    // Topbar
    goodMorning: "Good Morning",
    goodAfternoon: "Good Afternoon",
    goodEvening: "Good Evening",
    welcomeMessage: "Let's make your day meaningful.",
    offline: "You are Offline",
    offlineMessage: "Data will sync when internet is available.",
    alerts: "Alerts",

    // Voice Companion
    voiceCompanion: "Smriti – Your Voice Companion",
    voiceDescription: "I can talk, listen and help you with your day.",
    speakLanguage: "Speak in your language.",
    tapToSpeak: "Tap to Speak",
    typeMessage: "Type a message",
    speakIn: "I speak in:",
    supportsLanguages:
      "Smriti supports Assamese, Khasi, Mizo, Manipuri, Bodo and 10+ regional languages.",

    // Daily Routine
    todaysRoutine: "Today's Routine",
    tellWhatsNext: "Tell me what's next",
    morningMedicine: "Morning Medicine",
    drinkWater: "Drink Water",
    lunchTime: "Lunch Time",
    brainActivity: "Brain Activity",
    eveningWalk: "Evening Walk",
    nightMedicine: "Night Medicine",
    completed: "Completed",
    pending: "Pending",
    viewFullRoutine: "View Full Routine",

    // Brain Activity
    todaysBrainActivity: "Today's Brain Activity",
    simpleActivities: "Simple activities for a healthy mind",
    recommendedToday: "Recommended for today",
    pictureMatch: "Picture Match",
    findPair: "Find the Pair",
    patternGame: "Pattern Game",
    memoryGame: "Memory game",
    attentionGame: "Attention game",
    thinkingGame: "Thinking game",
    easy: "Easy",
    minutes: "5 min",
    start: "Start",

    // Progress
    weeklyProgress: "This Week's Progress",
    activitiesCompleted: "Activities Completed",
    averageEngagement: "Average Engagement",
    memoryScore: "Memory Score",
    attentionLevel: "Attention Level",
    stable: "Stable",
    good: "Good",
    smritiInsight: "Smriti Insight",
    insightMessage:
      "You are doing great! Your memory game performance is stable this week. Keep staying active and happy!",
    viewDetailedProgress: "View Detailed Progress",

    // Safety
    safetyStatus: "Safety Status",
    safeZone: "Safe Zone",
    homeZone: "Home",
    lastCheckIn: "Last Check-in",
    minutesAgo: "20 min ago",
    allGood: "All Good",

    // Care Circle
    myCareCircle: "My Care Circle",
    available: "Available",
    lastSeen: "Last seen",
    visitTomorrow: "Visit tomorrow",
    daughter: "Daughter",
    son: "Son",
    communityHealthWorker: "Community Health Worker",
    viewAllMembers: "View All Members",

    // Memory Book
    myMemoryBook: "My Memory Book",
    myFamily: "My Family",
    specialMoments: "Special Moments",
    homeVillage: "My Home & Village",
    favoriteSounds: "Favorite Sounds",
    memories: "memories",
    sounds: "sounds",
    openMemoryBook: "Open Memory Book",

    // Bottom Status
    offlineMode: "Offline Mode",
    offlineAvailable: "All core features are available",
    lastSync: "Last Sync",
    needHelp: "Need Help?",
    talkToSmritiOrCaregiver: "Talk to Smriti or call your caregiver.",
    caregiversHealthWorkers: "For Caregivers & Health Workers",
    caregiverDescription: "Track, support and stay updated on your loved one's well-being.",
    openCaregiverView: "Open Caregiver View",

    // Emergency
    emergencyHelp: "Emergency Help",
    tapToCall: "Tap to call for help",
    helpline: "Helpline",
    worksOffline: "Works offline",

    // General
    dashboard: "Dashboard",
    close: "Close",
    more: "More",
  },

  as: {
    home: "হোম",
    brainGames: "মগজৰ খেল",
    talkToSmriti: "স্মৃতিৰ সৈতে কথা পাতক",
    dailyRoutine: "দৈনিক ৰুটিন",
    medicineHealth: "ঔষধ আৰু স্বাস্থ্য",
    memoryProgress: "স্মৃতিৰ অগ্ৰগতি",
    careCircle: "মোৰ যত্ন চক্র",
    safetyLocation: "সুৰক্ষা আৰু অৱস্থান",
    memoryBook: "স্মৃতিৰ কিতাপ",
    language: "ভাষা",
    helpSupport: "সহায় আৰু সমৰ্থন",
    settings: "ছেটিংছ",

    goodMorning: "সুপ্ৰভাত",
    goodAfternoon: "শুভ দুপৰীয়া",
    goodEvening: "শুভ সন্ধ্যা",
    welcomeMessage: "আপোনাৰ দিনটো অৰ্থপূৰ্ণ কৰি তোলোঁ।",
    offline: "আপুনি অফলাইনত আছে",
    offlineMessage: "ইণ্টাৰনেট উপলব্ধ হ'লে তথ্য ছিংক হ'ব।",
    alerts: "সতৰ্কবাণী",

    voiceCompanion: "স্মৃতি – আপোনাৰ কণ্ঠ সংগী",
    voiceDescription: "মই কথা পাতিব, শুনিব আৰু আপোনাৰ দৈনন্দিন কামত সহায় কৰিব পাৰোঁ।",
    speakLanguage: "আপোনাৰ ভাষাত কথা পাতক।",
    tapToSpeak: "কথা ক'বলৈ টিপক",
    typeMessage: "এটা বাৰ্তা লিখক",
    speakIn: "মই কওঁ:",
    supportsLanguages:
      "স্মৃতিয়ে অসমীয়া, খাছি, মিজো, মণিপুৰী, বড়ো আৰু ১০+ আঞ্চলিক ভাষা সমৰ্থন কৰে।",

    todaysRoutine: "আজিৰ ৰুটিন",
    tellWhatsNext: "পিছত কি আছে কওক",
    morningMedicine: "ৰাতিপুৱাৰ ঔষধ",
    drinkWater: "পানী খাওক",
    lunchTime: "দুপৰীয়াৰ আহাৰ",
    brainActivity: "মগজৰ কাৰ্যকলাপ",
    eveningWalk: "সন্ধিয়াৰ খোজ",
    nightMedicine: "ৰাতিৰ ঔষধ",
    completed: "সম্পূৰ্ণ",
    pending: "বাকি",
    viewFullRoutine: "সম্পূৰ্ণ ৰুটিন চাওক",

    todaysBrainActivity: "আজিৰ মগজৰ কাৰ্যকলাপ",
    simpleActivities: "সুস্থ মনৰ বাবে সহজ কাৰ্যকলাপ",
    recommendedToday: "আজিৰ বাবে পৰামৰ্শ",
    pictureMatch: "ছবি মিলাওক",
    findPair: "যোৰ বিচাৰক",
    patternGame: "নক্সাৰ খেল",
    memoryGame: "স্মৃতিৰ খেল",
    attentionGame: "মনোযোগৰ খেল",
    thinkingGame: "চিন্তাৰ খেল",
    easy: "সহজ",
    minutes: "৫ মিনিট",
    start: "আৰম্ভ কৰক",

    weeklyProgress: "এই সপ্তাহৰ অগ্ৰগতি",
    activitiesCompleted: "সম্পূৰ্ণ কাৰ্যকলাপ",
    averageEngagement: "গড় অংশগ্ৰহণ",
    memoryScore: "স্মৃতিৰ স্ক'ৰ",
    attentionLevel: "মনোযোগৰ স্তৰ",
    stable: "স্থিৰ",
    good: "ভাল",
    smritiInsight: "স্মৃতিৰ পৰামৰ্শ",
    insightMessage: "আপুনি ভাল কৰি আছে! এই সপ্তাহত আপোনাৰ স্মৃতিৰ খেলৰ প্ৰদৰ্শন স্থিৰ আছে।",
    viewDetailedProgress: "বিস্তৃত অগ্ৰগতি চাওক",

    safetyStatus: "সুৰক্ষাৰ অৱস্থা",
    safeZone: "সুৰক্ষিত স্থান",
    homeZone: "ঘৰ",
    lastCheckIn: "শেষ চেক-ইন",
    minutesAgo: "২০ মিনিট আগতে",
    allGood: "সকলো ভাল",

    myCareCircle: "মোৰ যত্ন চক্র",
    available: "উপলব্ধ",
    lastSeen: "শেষ দেখা",
    visitTomorrow: "কাইলৈ দেখা কৰিব",
    daughter: "জীয়েক",
    son: "পুত্ৰ",
    communityHealthWorker: "সামূহিক স্বাস্থ্য কৰ্মী",
    viewAllMembers: "সকলো সদস্য চাওক",

    myMemoryBook: "মোৰ স্মৃতিৰ কিতাপ",
    myFamily: "মোৰ পৰিয়াল",
    specialMoments: "বিশেষ মুহূৰ্ত",
    homeVillage: "মোৰ ঘৰ আৰু গাঁও",
    favoriteSounds: "প্ৰিয় শব্দ",
    memories: "স্মৃতি",
    sounds: "শব্দ",
    openMemoryBook: "স্মৃতিৰ কিতাপ খোলক",

    offlineMode: "অফলাইন মোড",
    offlineAvailable: "সকলো মূল সুবিধা উপলব্ধ",
    lastSync: "শেষ ছিংক",
    needHelp: "সহায় লাগে?",
    talkToSmritiOrCaregiver: "স্মৃতিৰ সৈতে কথা পাতক বা আপোনাৰ যত্নদাতাক ফোন কৰক।",
    caregiversHealthWorkers: "যত্নদাতা আৰু স্বাস্থ্য কৰ্মীৰ বাবে",
    caregiverDescription: "আপোনাৰ আপোনজনৰ অৱস্থা অনুসৰণ আৰু সহায় কৰক।",
    openCaregiverView: "যত্নদাতা ভিউ খোলক",

    emergencyHelp: "জৰুৰী সহায়",
    tapToCall: "সহায়ৰ বাবে ফোন কৰিবলৈ টিপক",
    helpline: "হেল্পলাইন",
    worksOffline: "অফলাইনত কাম কৰে",

    dashboard: "ডেশ্বব'ৰ্ড",
    close: "বন্ধ কৰক",
    more: "আৰু",
  },

  // Placeholder translations - replace later with verified native translations
  kh: {
    home: "Home",
    brainGames: "Brain Games",
    talkToSmriti: "Talk to Care Agent",
    dailyRoutine: "Daily Routine",
    medicineHealth: "Medicine & Health",
    memoryProgress: "Memory Progress",
    careCircle: "My Care Circle",
    safetyLocation: "Safety & Location",
    memoryBook: "Memory Book",
    language: "Language",
    helpSupport: "Help & Support",
    settings: "Settings",

    goodMorning: "Good Morning",
    goodAfternoon: "Good Afternoon",
    goodEvening: "Good Evening",
    welcomeMessage: "Let's make your day meaningful.",
    offline: "You are Offline",
    offlineMessage: "Data will sync when internet is available.",
    alerts: "Alerts",

    voiceCompanion: "Smriti – Your Voice Companion",
    voiceDescription: "I can talk, listen and help you with your day.",
    speakLanguage: "Speak in your language.",
    tapToSpeak: "Tap to Speak",
    typeMessage: "Type a message",
    speakIn: "I speak in:",
    supportsLanguages:
      "Smriti supports Assamese, Khasi, Mizo, Manipuri, Bodo and 10+ regional languages.",

    todaysRoutine: "Today's Routine",
    tellWhatsNext: "Tell me what's next",
    morningMedicine: "Morning Medicine",
    drinkWater: "Drink Water",
    lunchTime: "Lunch Time",
    brainActivity: "Brain Activity",
    eveningWalk: "Evening Walk",
    nightMedicine: "Night Medicine",
    completed: "Completed",
    pending: "Pending",
    viewFullRoutine: "View Full Routine",

    todaysBrainActivity: "Today's Brain Activity",
    simpleActivities: "Simple activities for a healthy mind",
    recommendedToday: "Recommended for today",
    pictureMatch: "Picture Match",
    findPair: "Find the Pair",
    patternGame: "Pattern Game",
    memoryGame: "Memory game",
    attentionGame: "Attention game",
    thinkingGame: "Thinking game",
    easy: "Easy",
    minutes: "5 min",
    start: "Start",

    weeklyProgress: "This Week's Progress",
    activitiesCompleted: "Activities Completed",
    averageEngagement: "Average Engagement",
    memoryScore: "Memory Score",
    attentionLevel: "Attention Level",
    stable: "Stable",
    good: "Good",
    smritiInsight: "Smriti Insight",
    insightMessage:
      "You are doing great! Your memory game performance is stable this week.",
    viewDetailedProgress: "View Detailed Progress",

    safetyStatus: "Safety Status",
    safeZone: "Safe Zone",
    homeZone: "Home",
    lastCheckIn: "Last Check-in",
    minutesAgo: "20 min ago",
    allGood: "All Good",

    myCareCircle: "My Care Circle",
    available: "Available",
    lastSeen: "Last seen",
    visitTomorrow: "Visit tomorrow",
    daughter: "Daughter",
    son: "Son",
    communityHealthWorker: "Community Health Worker",
    viewAllMembers: "View All Members",

    myMemoryBook: "My Memory Book",
    myFamily: "My Family",
    specialMoments: "Special Moments",
    homeVillage: "My Home & Village",
    favoriteSounds: "Favorite Sounds",
    memories: "memories",
    sounds: "sounds",
    openMemoryBook: "Open Memory Book",

    offlineMode: "Offline Mode",
    offlineAvailable: "All core features are available",
    lastSync: "Last Sync",
    needHelp: "Need Help?",
    talkToSmritiOrCaregiver: "Talk to Smriti or call your caregiver.",
    caregiversHealthWorkers: "For Caregivers & Health Workers",
    caregiverDescription: "Track and support your loved one's well-being.",
    openCaregiverView: "Open Caregiver View",

    emergencyHelp: "Emergency Help",
    tapToCall: "Tap to call for help",
    helpline: "Helpline",
    worksOffline: "Works offline",

    dashboard: "Dashboard",
    close: "Close",
    more: "More",
  },

  mz: {
    home: "Home",
    brainGames: "Brain Games",
    talkToSmriti: "Talk to Care Agent",
    dailyRoutine: "Daily Routine",
    medicineHealth: "Medicine & Health",
    memoryProgress: "Memory Progress",
    careCircle: "My Care Circle",
    safetyLocation: "Safety & Location",
    memoryBook: "Memory Book",
    language: "Language",
    helpSupport: "Help & Support",
    settings: "Settings",

    goodMorning: "Good Morning",
    goodAfternoon: "Good Afternoon",
    goodEvening: "Good Evening",
    welcomeMessage: "Let's make your day meaningful.",
    offline: "You are Offline",
    offlineMessage: "Data will sync when internet is available.",
    alerts: "Alerts",

    voiceCompanion: "Smriti – Your Voice Companion",
    voiceDescription: "I can talk, listen and help you with your day.",
    speakLanguage: "Speak in your language.",
    tapToSpeak: "Tap to Speak",
    typeMessage: "Type a message",
    speakIn: "I speak in:",

    todaysRoutine: "Today's Routine",
    tellWhatsNext: "Tell me what's next",
    morningMedicine: "Morning Medicine",
    drinkWater: "Drink Water",
    lunchTime: "Lunch Time",
    brainActivity: "Brain Activity",
    eveningWalk: "Evening Walk",
    nightMedicine: "Night Medicine",
    completed: "Completed",
    pending: "Pending",
    viewFullRoutine: "View Full Routine",

    todaysBrainActivity: "Today's Brain Activity",
    simpleActivities: "Simple activities for a healthy mind",
    recommendedToday: "Recommended for today",
    pictureMatch: "Picture Match",
    findPair: "Find the Pair",
    patternGame: "Pattern Game",
    memoryGame: "Memory game",
    attentionGame: "Attention game",
    thinkingGame: "Thinking game",
    easy: "Easy",
    minutes: "5 min",
    start: "Start",

    weeklyProgress: "This Week's Progress",
    activitiesCompleted: "Activities Completed",
    averageEngagement: "Average Engagement",
    memoryScore: "Memory Score",
    attentionLevel: "Attention Level",
    stable: "Stable",
    good: "Good",
    smritiInsight: "Smriti Insight",
    insightMessage: "You are doing great!",
    viewDetailedProgress: "View Detailed Progress",

    safetyStatus: "Safety Status",
    safeZone: "Safe Zone",
    homeZone: "Home",
    lastCheckIn: "Last Check-in",
    minutesAgo: "20 min ago",
    allGood: "All Good",

    myCareCircle: "My Care Circle",
    available: "Available",
    lastSeen: "Last seen",
    visitTomorrow: "Visit tomorrow",
    daughter: "Daughter",
    son: "Son",
    communityHealthWorker: "Community Health Worker",
    viewAllMembers: "View All Members",

    myMemoryBook: "My Memory Book",
    myFamily: "My Family",
    specialMoments: "Special Moments",
    homeVillage: "My Home & Village",
    favoriteSounds: "Favorite Sounds",
    memories: "memories",
    sounds: "sounds",
    openMemoryBook: "Open Memory Book",

    offlineMode: "Offline Mode",
    offlineAvailable: "All core features are available",
    lastSync: "Last Sync",
    needHelp: "Need Help?",
    talkToSmritiOrCaregiver: "Talk to Smriti or call your caregiver.",
    caregiversHealthWorkers: "For Caregivers & Health Workers",
    caregiverDescription: "Track and support your loved one's well-being.",
    openCaregiverView: "Open Caregiver View",

    emergencyHelp: "Emergency Help",
    tapToCall: "Tap to call for help",
    helpline: "Helpline",
    worksOffline: "Works offline",

    dashboard: "Dashboard",
    close: "Close",
    more: "More",
  },

  mn: {
    home: "Home",
    brainGames: "Brain Games",
    talkToSmriti: "Talk to Care Agent",
    dailyRoutine: "Daily Routine",
    medicineHealth: "Medicine & Health",
    memoryProgress: "Memory Progress",
    careCircle: "My Care Circle",
    safetyLocation: "Safety & Location",
    memoryBook: "Memory Book",
    language: "Language",
    helpSupport: "Help & Support",
    settings: "Settings",

    goodMorning: "Good Morning",
    goodAfternoon: "Good Afternoon",
    goodEvening: "Good Evening",
    welcomeMessage: "Let's make your day meaningful.",
    offline: "You are Offline",
    offlineMessage: "Data will sync when internet is available.",
    alerts: "Alerts",

    voiceCompanion: "Smriti – Your Voice Companion",
    voiceDescription: "I can talk, listen and help you with your day.",
    speakLanguage: "Speak in your language.",
    tapToSpeak: "Tap to Speak",
    typeMessage: "Type a message",
    speakIn: "I speak in:",

    todaysRoutine: "Today's Routine",
    tellWhatsNext: "Tell me what's next",
    morningMedicine: "Morning Medicine",
    drinkWater: "Drink Water",
    lunchTime: "Lunch Time",
    brainActivity: "Brain Activity",
    eveningWalk: "Evening Walk",
    nightMedicine: "Night Medicine",
    completed: "Completed",
    pending: "Pending",
    viewFullRoutine: "View Full Routine",

    todaysBrainActivity: "Today's Brain Activity",
    simpleActivities: "Simple activities for a healthy mind",
    recommendedToday: "Recommended for today",
    pictureMatch: "Picture Match",
    findPair: "Find the Pair",
    patternGame: "Pattern Game",
    memoryGame: "Memory game",
    attentionGame: "Attention game",
    thinkingGame: "Thinking game",
    easy: "Easy",
    minutes: "5 min",
    start: "Start",

    weeklyProgress: "This Week's Progress",
    activitiesCompleted: "Activities Completed",
    averageEngagement: "Average Engagement",
    memoryScore: "Memory Score",
    attentionLevel: "Attention Level",
    stable: "Stable",
    good: "Good",
    smritiInsight: "Smriti Insight",
    insightMessage: "You are doing great!",
    viewDetailedProgress: "View Detailed Progress",

    safetyStatus: "Safety Status",
    safeZone: "Safe Zone",
    homeZone: "Home",
    lastCheckIn: "Last Check-in",
    minutesAgo: "20 min ago",
    allGood: "All Good",

    myCareCircle: "My Care Circle",
    available: "Available",
    lastSeen: "Last seen",
    visitTomorrow: "Visit tomorrow",
    daughter: "Daughter",
    son: "Son",
    communityHealthWorker: "Community Health Worker",
    viewAllMembers: "View All Members",

    myMemoryBook: "My Memory Book",
    myFamily: "My Family",
    specialMoments: "Special Moments",
    homeVillage: "My Home & Village",
    favoriteSounds: "Favorite Sounds",
    memories: "memories",
    sounds: "sounds",
    openMemoryBook: "Open Memory Book",

    offlineMode: "Offline Mode",
    offlineAvailable: "All core features are available",
    lastSync: "Last Sync",
    needHelp: "Need Help?",
    talkToSmritiOrCaregiver: "Talk to Smriti or call your caregiver.",
    caregiversHealthWorkers: "For Caregivers & Health Workers",
    caregiverDescription: "Track and support your loved one's well-being.",
    openCaregiverView: "Open Caregiver View",

    emergencyHelp: "Emergency Help",
    tapToCall: "Tap to call for help",
    helpline: "Helpline",
    worksOffline: "Works offline",

    dashboard: "Dashboard",
    close: "Close",
    more: "More",
  },

  bd: {
    home: "Home",
    brainGames: "Brain Games",
    talkToSmriti: "Talk to Care Agent",
    dailyRoutine: "Daily Routine",
    medicineHealth: "Medicine & Health",
    memoryProgress: "Memory Progress",
    careCircle: "My Care Circle",
    safetyLocation: "Safety & Location",
    memoryBook: "Memory Book",
    language: "Language",
    helpSupport: "Help & Support",
    settings: "Settings",

    goodMorning: "Good Morning",
    goodAfternoon: "Good Afternoon",
    goodEvening: "Good Evening",
    welcomeMessage: "Let's make your day meaningful.",
    offline: "You are Offline",
    offlineMessage: "Data will sync when internet is available.",
    alerts: "Alerts",

    voiceCompanion: "Smriti – Your Voice Companion",
    voiceDescription: "I can talk, listen and help you with your day.",
    speakLanguage: "Speak in your language.",
    tapToSpeak: "Tap to Speak",
    typeMessage: "Type a message",
    speakIn: "I speak in:",

    todaysRoutine: "Today's Routine",
    tellWhatsNext: "Tell me what's next",
    morningMedicine: "Morning Medicine",
    drinkWater: "Drink Water",
    lunchTime: "Lunch Time",
    brainActivity: "Brain Activity",
    eveningWalk: "Evening Walk",
    nightMedicine: "Night Medicine",
    completed: "Completed",
    pending: "Pending",
    viewFullRoutine: "View Full Routine",

    todaysBrainActivity: "Today's Brain Activity",
    simpleActivities: "Simple activities for a healthy mind",
    recommendedToday: "Recommended for today",
    pictureMatch: "Picture Match",
    findPair: "Find the Pair",
    patternGame: "Pattern Game",
    memoryGame: "Memory game",
    attentionGame: "Attention game",
    thinkingGame: "Thinking game",
    easy: "Easy",
    minutes: "5 min",
    start: "Start",

    weeklyProgress: "This Week's Progress",
    activitiesCompleted: "Activities Completed",
    averageEngagement: "Average Engagement",
    memoryScore: "Memory Score",
    attentionLevel: "Attention Level",
    stable: "Stable",
    good: "Good",
    smritiInsight: "Smriti Insight",
    insightMessage: "You are doing great!",
    viewDetailedProgress: "View Detailed Progress",

    safetyStatus: "Safety Status",
    safeZone: "Safe Zone",
    homeZone: "Home",
    lastCheckIn: "Last Check-in",
    minutesAgo: "20 min ago",
    allGood: "All Good",

    myCareCircle: "My Care Circle",
    available: "Available",
    lastSeen: "Last seen",
    visitTomorrow: "Visit tomorrow",
    daughter: "Daughter",
    son: "Son",
    communityHealthWorker: "Community Health Worker",
    viewAllMembers: "View All Members",

    myMemoryBook: "My Memory Book",
    myFamily: "My Family",
    specialMoments: "Special Moments",
    homeVillage: "My Home & Village",
    favoriteSounds: "Favorite Sounds",
    memories: "memories",
    sounds: "sounds",
    openMemoryBook: "Open Memory Book",

    offlineMode: "Offline Mode",
    offlineAvailable: "All core features are available",
    lastSync: "Last Sync",
    needHelp: "Need Help?",
    talkToSmritiOrCaregiver: "Talk to Smriti or call your caregiver.",
    caregiversHealthWorkers: "For Caregivers & Health Workers",
    caregiverDescription: "Track and support your loved one's well-being.",
    openCaregiverView: "Open Caregiver View",

    emergencyHelp: "Emergency Help",
    tapToCall: "Tap to call for help",
    helpline: "Helpline",
    worksOffline: "Works offline",

    dashboard: "Dashboard",
    close: "Close",
    more: "More",
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState("en");

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t,
        translations,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);

  if (!context) {
    throw new Error(
      "useLanguage must be used inside LanguageProvider"
    );
  }

  return context;
};