#!/usr/bin/env python3
"""Build a pool of phonetic (sound-alike / wordplay) jokes for Smriti.

Run from repo root:
    python3 scripts/phonetic_jokes.py

Writes src/data/phoneticJokes.js. Live prompt samples a shuffled subset.

Tell these the way a person would: ONE spoken paragraph. No named two-character
skits (Rahul/Vinod, Teacher:/Banta: play scripts). No “sahi hai na / kaisa laga”.
"""

from __future__ import annotations

import json
import random
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_JS = ROOT / "src" / "data" / "phoneticJokes.js"

# Spoken paragraphs. Phonetic / sound-alike. Not college-canteen dialogue.
SEED_JOKES = [
    "Teacher poochhti hai electricity ka opposite. Banta sochta hai, phir muskurata hai — Guest-ricity. Matlab ghar mein light nahi, guest aa rahe hain.",
    "Padosi WiFi maangta hai. Santa kagaz pe likh ke deta hai WRONG. Padosi type karta hai, kaam nahi karta. Santa quietly, maine kaha tha, wrong hai.",
    "Santa chemist se sleeping tablets maangta hai, kitni, poochhta chemist. Santa kehta hai woh toh neend aane ke baad gin loonga.",
    "Santa library mein board padhta hai Silence please, phir dheere se chillata hai Silence please. Librarian dekhta hai, Santa, isliye toh dheere se chillaya.",
    "Time kya hua, poochhta Santa. Banta ghadi dekhta hai, jo kal tha usse thoda aage. Matlab late nahi, just aage.",
    "Santa lift ka button poochhta hai, jo upar jaaye wala. Banta kehta hai mood nahi jaa raha, floor jaayega.",
    "Shopkeeper packet extra charge. Santa sochta hai, phir haath mein hi le jaata hai — pocket mein packet.",
    "Neighbour poochhta hai paani gaya kya. Santa tanki dekhta hai, nahi, paani aata hai, jaata tanki mein. Matlab geography hai.",
    "Santa photocopy, do copy, colour. Jo original mein hai uski bhi do, kehta hai. Shop wala original ko hi duplicate samajh baitha.",
    "Teacher spell wrong maangti hai. Santa likhta hai R O N G. That's wrong, kehti teacher. Santa, wahi toh aapne maanga tha.",
    "Banta waterproof watch leta hai, phir usse paani peene ki koshish. Seller kehta hai watch peene ke liye nahi. Banta, word mein water tha, hope extra thi.",
    "Santa chhata kholta hai, kapda missing. Yeh chhata nahi, chhata ka skeleton. Um-brella — um matlab shak, rain sure.",
    "Teacher sentence with I. Santa bolta hai I, phir I full stop. Class bhi full stop feel karti hai.",
    "Aita tamul deti hai. Santa, pehle ta phir mul, do bill. Aita, ek hi cheez do syllable. Santa, discount on extra syllable.",
    "Santa TV remote dhoondhta hai sofa, fridge, phir apne haath mein. Remote ne mujhe dhoondha, search complete, spelling also.",
    "Pencil 2B hai, poochhta Santa. 2B or not 2B. Shop, Hamlet nahi stationery. Drama cheap, graphite costly.",
    "Banta biscuit chai mein doobata hai, biscuit toot jaata hai. Trust issues chai se, biscuit ne swimming nahi seekhi.",
    "Password hint, first pet. Santa types Fridge. Fail. Second pet bhi fridge. Hungry security.",
    "Santa soap floating hai, freshness floats. Soap paani mein doob gaya. Advertisement phonetic, physics strict.",
    "Buy one get one. Santa, get one kahan packed hai. Shopkeeper, concept mein. Santa, concept ghar nahi jaata.",
    "Assam chai kettle pe late. Aita, tum roz late. Chai, Assam wali hoon, flavour aane do. VIP guest, not instant.",
    "Shillong walk, sweater teen layer. Calendar pe summer hai. Calendar Delhi ka hai. Cloud local boss, English optional.",
    "Santa bus ticket, jitni dikhati hoon, kehta conductor. Santa, toh dikhao mat, sasta padega. Conductor ticket chhupaata hai.",
    "Watch waterproof nahi, WiFi WRONG, Guest-ricity — shabdon ka khel, stage play nahi. Ek saans mein punch, phir chup.",
]


def unique_keep_order(items: list[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for item in items:
        key = " ".join(item.split())
        if key in seen:
            continue
        seen.add(key)
        out.append(item)
    return out


def write_js(jokes: list[str], examples: list[str]) -> None:
    OUT_JS.parent.mkdir(parents=True, exist_ok=True)
    examples_json = json.dumps(examples, ensure_ascii=False, indent=2)
    jokes_json = json.dumps(jokes, ensure_ascii=False, indent=2)
    OUT_JS.write_text(
        f"""/** Phonetic / wordplay jokes (Roman script) — spoken paragraphs, not skits.
 * Generated by scripts/phonetic_jokes.py — expand the bank there, not in the Live prompt.
 * One human breath. No Rahul/Vinod scripts. No “sahi hai na / kaisa laga”.
 */
export const PHONETIC_JOKE_EXAMPLES = {examples_json};

export const PHONETIC_JOKES = {jokes_json};

export function pickPhoneticJokeExamples(count = 8) {{
  const pool = PHONETIC_JOKES.slice();
  for (let i = pool.length - 1; i > 0; i--) {{
    const j = Math.floor(Math.random() * (i + 1));
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }}
  return pool.slice(0, Math.min(count, pool.length));
}}
""",
        encoding="utf-8",
    )


def main() -> None:
    jokes = unique_keep_order(SEED_JOKES)
    # Fixed examples so the model always sees Guest-ricity / WiFi WRONG, not dialogue.
    examples = jokes[:8]
    write_js(jokes, examples)
    print(f"Wrote {len(jokes)} jokes ({len(examples)} prompt examples) -> {OUT_JS}")


if __name__ == "__main__":
    main()
