INSERT INTO memories (id, title, body, photo_url, person, place, memory_date, lang, album) VALUES
('tea-garden-dew', 'Dew in the tea garden',
 'Latveria was still a girl when the garden woke before the sun. The rows of tea ran like a wet green sea down the slope. Dew clung to her ankles like cold glass bangles. A hornbill called once from the shade tree, then went quiet.',
 '/photos/garden.png', 'Latveria', 'Tea garden, Assam', '1968-03-12', 'en', 'My Home & Village'),
('gamosa-sister', 'Sister’s gamosa',
 'Her sister walked ahead with a gamosa tied at her waist, red border bright. The pluckers’ baskets bumped softly against the leaves. They were not rich. They were early. The dew was the first wage, and nobody wrote it in a ledger.',
 '/photos/rina.png', 'Sister', 'Garden slope', '1968-03-12', 'en', 'My Family'),
('factory-chimney', 'The factory chimney',
 'Far below, the factory chimney breathed iron. By mid-morning the leaf smell turned sweet and crushed. Latveria still smells that leaf when rain starts on Zoo Road.',
 '/photos/home.png', 'Latveria', 'Below the garden', '1969-07-04', 'en', 'My Home & Village'),
('doom-bihu', 'Doom’s first dhol',
 'Doom was small enough to hide behind the dhol. The courtyard in Guwahati filled with Bihu steps and the smell of pitha. Latveria kept one hand on his shoulder so he would not run into the drum.',
 '/photos/latveria.png', 'Doom', 'Courtyard, Guwahati', '1989-04-14', 'en', 'Special Moments'),
('zoo-road-evening', 'Evening on Zoo Road',
 'The bus from the garden used to leave them near Zoo Road. Rina would wait with a steel tiffin. Street lamps came on one by one. Home was the gate with the loose latch, not a pin on a map.',
 '/photos/home.png', 'Rina', 'Zoo Road, Guwahati', '1996-11-02', 'en', 'My Home & Village'),
('sunday-tea', 'Sunday tea with Rina',
 'Rina pours the second cup without asking. Two spoons, no sugar for Latveria now. They sit by the window and name the birds they can still name. That is the whole visit.',
 '/photos/rina.png', 'Rina', 'Home kitchen', '2024-01-21', 'en', 'My Family'),
('asha-visit', 'Mina from the health centre',
 'Mina the ASHA worker leaves her slippers at the door. She checks the strip of tablets and talks to Latveria about water, not about scores. Doom makes tea for her the way the garden taught him — strong, and not in a hurry.',
 '/photos/latveria.png', 'Mina', 'Home — Zoo Road', '2025-08-10', 'en', 'Special Moments'),
('radio-evening', 'The old radio',
 'The radio still lives on the shelf above the kettle. In the evening someone turns it low. Latveria says the announcer’s voice is like the one from Dispur years ago. Nobody argues. The kettle clicks off and that is enough music.',
 '/photos/mark.png', 'Latveria', 'Sitting room', '2012-08-18', 'en', 'Favorite Sounds')
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  body = EXCLUDED.body,
  photo_url = EXCLUDED.photo_url,
  person = EXCLUDED.person,
  place = EXCLUDED.place,
  memory_date = EXCLUDED.memory_date,
  lang = EXCLUDED.lang,
  album = EXCLUDED.album;
